version: '2'
services:
  sandbox.web:
    build:
      context: jeevanrpro/account-management-client
      args:
        env: sandbox
    ports:
      - "4200:80"
  app.web:
    build:
      context: jeevanrpro/account-management-client
      args:
        env: prod
    ports:
      - "4201:80"
